version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - monitoreo
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoreo
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoreo
networks:
  monitoreo:

